### ISSUE TITLE
VS Template installation script doesn't work if Documents folder is not in user folder

### ISSUE THREAD

**Issue by TMVector** [bryanedds/Nu#165]
The "Documents" folder in Windows is not neccesarily located in the folder given by `%userprofile%`. The install script is ineffective in such a case, as the script copies the template zip to `"%userprofile%\Documents\Visual Studio 2015\Templates\ProjectTemplates"`

Although there no environment variable for this folder AFAIK, switching to a PowerShell script would solve this as `[Environment]::GetFolderPath("mydocuments")` does return the correct path (at least on Win10).

**Comment by bryanedds** [comment]
Thanks for raising this! I'll try to take care of this ASAP.

BTW - is this happening on default Win10 installs, or only after the user customizes the placement of `My Documents`?

**Comment by TMVector** [comment]
AFIAK it is only when the user changes the location.

Thanks for the quick response!

**Comment by bryanedds** [comment]
I don't think it is worth supporting this after all.
