### ISSUE TITLE
Consider converting Nu to .NET Core.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#220]
Nu is more than just a library. It is a collection of programs as well as a base library. To convert Nu to .NET Core, we need to convert multiple things.

The first thing that would need conversion would be Nu's base library, Prime -

https://github.com/bryanedds/Prime

Prime actually current works in .NET Core programs with a just compiler warning, `warning NU1701: Package 'Prime 3.2.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=vX.X'. This package may not be fully compatible with your project.` It advises a potential compatibility issue, but there is none found in practice. So converting Prime should be pretty straight-forward as it already works in a .NET Core VM.

The next thing to convert is the Nu engine library itself. The trick part here includes finding a way to treat the SDL2 dependencies in a platform-agnostic way. The first requirement will likely be to fork and convert the SDL2-CS (SDL2#) library from `netstandard2.0` to .NET Core. Then we have to figure out how to deploy the correct SDL2 native dlls rather than the Windows-specific ones currently hard-coded in the Nu.fsproj file.

After that, we have to ensure that the existing builds of the following existing dependencies work on the various platforms when running .NET Core -

FarseerPhysics (a .NET Framework dll)
FParsec (a .NET Standard dll)
FSCheck / FSCheck.Xunit (I'm not sure what these are)
Magick.NET (a .NET Framework dll)
FSharpx (.NET Framework dlls)
TiledSharp (a .NET Framework dll)

I don't think we'll have to fork and convert these libraries to .NET Core, but it may be possible. Each of these libraries are themselves relatively dependency-free, so converting them is not likely a big deal if required.

You'll notice that some of Nu's dependencies are stored in the repo (in Nu\Nu\Nu.Dependencies) rather than pulled from a nuget source. These include -

Farseer
FSharpx
Magick.NET
Nite.Collections.Deque
Scintilla.NET
SDL2#
TiledSharp

It would probably be worth updating these to get their nuget-provided versions, but I'm not sure if that is critical.

The next thing to consider is the conversion of Gaia, Nu's world editor. Gaia is built on WinForms and as such, there's no way to convert it from Windows. This makes deployment of Nu available for all platforms but interactive development for Nu possible only on Windows. Because Gaia is Windows-only and there is no known roadmap for a cross-platform WinForms - and because Gaia is practically essential to developing Nu applications - there is no story for developing Nu applications on platforms other than Windows. The only alternative would be to rewrite Gaia for a cross platform desktop UI like Xamarin.Forms, but I don't have much confidence that solution could be made sufficient - in addition to the high cost of a rewrite.

TODO: More details on conversion.

**Comment by bryanedds** [comment]
UPDATE: porting Nu to .NET Core is currently de-prioritized, but there has been some incidental progress on this item. Primarily, all of the dependencies except Scintilla for Gaia have be moved to nuget.

**Comment by ImaginaryDevelopment** [comment]
> except Scintilla for Gaia have be moved to nuget.

Is this "have to be moved", or "have been moved" ?

**Comment by bryanedds** [comment]
"have been moved", I meant :)

No updates here as of yet. Mono seems to be an adequate solution for now and there's currently no resources to do the porting.

**Comment by bryanedds** [comment]
Screw .Net Core, we went straight to .Net 7!
