### ISSUE TITLE
Setting a position of Entity with a RigidBodyFacet

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#249]
I trying to create a entity in LayerDispatcher
```fsharp
type MainLayerDispatcher () =
  inherit LayerDispatcher ()
  
  override this.Register (layer, world) =
    let player1, world = World.createEntity<PlayerEntityDispatcher> (Some Simulants.Player.EntityName) DefaultOverlay layer world
    let fountain, world = World.createEntity<StaticEntityDispatcher> (Some Simulants.Fountain.EntityName) DefaultOverlay layer world
    
    let world = player1.SetPosition (Vector2(0.0f, 0.0f)) world
    let world = fountain.SetPosition (Vector2(96.0f, 96.0f)) world
    
    world
```
It works, but after i tried to add a RigidBodyFacet to them SetPosition stop working and only works inside a World events, like KeyboardKeyDown (i am using it for moving, and it works)
How must i place a entities in the world?

**Comment by bryanedds** [comment]
For non-physics entities, you are doing it right. For physics entities, you also need to call PropagatePhysics after setting the entity's position like so -

`let world = bullet.PropagatePhysics world`

Otherwise, the physics engine won't be given notification of where you want the body to be placed.

**Comment by bryanedds** [comment]
Also, you should't use SetPosition just to move a physics body. You only use SetPosition on a physics body when you are initially placing it (as above) or if you have to warp it. Instead, you want to apply a force like so -

```
            let physicsId = player.GetPhysicsId world
            let world = World.applyBodyForce (Vector2 (walkForce, 0.0f)) physicsId world
```

**Comment by bryanedds** [comment]
I presume this is resolved.
