### ISSUE TITLE
both wiki links are broken

### ISSUE THREAD

**Issue by dallinbeutler** [bryanedds/Nu#257]
If you click on the wiki, both links present in the wiki send you to a 404 message.

**Comment by bryanedds** [comment]
Oh, wow, I totally forgot I even used the wiki functionality :)

I'll update this as soon as I get a moment.

Cheers!

**Comment by bryanedds** [comment]
All of the relevant information is now on the main page, so I just want ahead and blanked the wiki page.

Thanks for reporting!
