### ISSUE TITLE
Some conceptual questions

### ISSUE THREAD

**Issue by njlr** [bryanedds/Nu#262]
Hello,

I was wondering if you could help me understand how Nu works a bit better. 

 1. What is a dispatcher?
 2. What is a stimulant?
 3. What is a layer?
 4. How do I represent the game state? Do I write my own Record / Discriminated union type?
 5. I read that this engine is purely functional at the high-level but it supports destructive updates at the low-level. Would you be able to go into more detail about how this works?
 
Sorry if these questions are already answered in the docs.

**Comment by bryanedds** [comment]
Although the docs are not nearly as complete as I'd like them to be, I think you should definitely turn to them first for these questions. It also shows you some examples to help get your head around the concepts -

https://github.com/bryanedds/Nu/blob/master/Nu/Nu.Documentation/Nu%20Game%20Engine.pdf

Feel free to follow up after reading the docs, but for now, I will close this issue.
