### ISSUE TITLE
CJK (Chinese, Japanese, Korean) text doesn't render

### ISSUE THREAD

**Issue by reinux** [bryanedds/Nu#539]
Tried downloading .ttf versions of [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP) and saving it as "NotoSansJP-Regular.024.ttf", referring to it in the asset graph.

![image](https://github.com/bryanedds/Nu/assets/5127297/4396f43a-5c9a-4d26-af03-be53e6b5b804)

(Not too sure what the .024 in the filename denotes, but it seems to be necessary, so I threw it in. I don't think that's what's causing it to fail, is it?)

**Comment by bryanedds** [comment]
The .024 tells the engine what the resolution of the text should be, so that's why it's necessary.

As for why non-english characters aren't rendering, I'm guessing it's a limitation of SDL's TTF_RenderText_Blended. There are alternatives that Nu could use like TTF_RenderUNICODE_Blended. I'll give it a shot and see.

**Comment by bryanedds** [comment]
Okay, I tried the TTF_RenderUNICODE_Blended function and have some japanese text rendering -

![image](https://github.com/bryanedds/Nu/assets/1625560/125ecdf1-4e18-4e72-b258-c615bfe30b11)

However, as you can see, it isn't centering properly.

**Comment by bryanedds** [comment]
Ah, needed to change one more function call to `TTF_SizeUNICODE`. Looks like it's working now -

![image](https://github.com/bryanedds/Nu/assets/1625560/9fc0676f-5401-4493-bb2c-0bca730eb399)

I'll push this to master and you can close this issue if it's working on your end, too!

**Comment by reinux** [comment]
Nice! That did the trick.

![image](https://github.com/bryanedds/Nu/assets/5127297/dcc9a909-4c7e-460d-a146-6cf15b71b42a)

(Don't mind the awkward clip at the bottom left, I'm on RDP.)

There's also a lot of typographical stuff that Japanese games like to use, like [ruby text](https://duckduckgo.com/?t=ffab&q=japanese+ruby+text&atb=v360-1&iax=images&ia=images) both to serve as phonetic guides as well as to indicate double meanings, especially in scifi/fantasy. I should be able to contribute in this area at some point later.
