### ISSUE TITLE
Consider using Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by reinux** [bryanedds/Nu#552]
.NET Core has a new [logging package](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line) built in that may be worth exploring so that logging can be made asynchronous while still being able to catch outputs immediately prior to a crash (in theory). This is the one ASP.NET uses.

The question I think would be whether it's worth having it in Nu itself, since the user could load the package in themselves.

On the other hand, semi-enforcing a logging mechanism the way ASP does might have the advantage of being able to coherently consolidate the logs, as well as having them show up in Gaia, for instance.

**Comment by bryanedds** [comment]
Ya, this is a good point. We really do need to stream log stuff to Gaia like Unity does... Let's definitely dig into this during this current implementation phase.

**Comment by bryanedds** [comment]
Let's deprioritise this a bit since it's not likely to get into the current dev phase.

**Comment by bryanedds** [comment]
Nu's logging has been adequate in all cases so far. Let's close unless we find a specific reason to pursue this.
