### ISSUE TITLE
SDL2 sprite rendering a big bottleneck in Nu.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#56]
Over the life of Nu, I never recorded sprite rendering as a bottleneck in Nu. But now that I've done the most important CPU optimizations, it sticks out by a large factor!

Fix this, likely by replacing SDL2 with bgfx - https://github.com/bkaradzic/bgfx

**Comment by bkaradzic** [comment]
:+1: Feel free to ask me any questions about bgfx.

**Comment by bryanedds** [comment]
Awesome you popped by!

Will do!
