### ISSUE TITLE
Gaia fails to find the template project on (at least some) linux machines

### ISSUE THREAD

**Issue by cwstra** [bryanedds/Nu#571]
More or less what it says on the tin (some linux machines being, of course, mine :wink: ). 

Debugging reveals that the calls to `Path.Simplify` seem to be generating a path without a leading `/`, so I suspect `Directory.Exists` is trying to find the template as a local path, rather than an absolute path. Furthermore, replacing the calls to `Path.Simplify` with `Path.GetFullPath` seems to fix the problem.

https://github.com/bryanedds/Nu/blob/06b1c4e35cf45d021898de59b41697ff47d68900/Nu/Nu.Gaia/Gaia.fs#L2238-L2239

**Comment by bryanedds** [comment]
There's an attempted fix in latest if you could test that out for me (remember to stash any of your local changes first!)

**Comment by bryanedds** [comment]
Should be fixed also by latest just calling Path.GetFullPath instead of the buggy Path.Simplify function (tho an attempted fix is in Prime master as well).

Close if you can confirm.

**Comment by cwstra** [comment]
Seems to do it!
