### ISSUE TITLE
Overlay-based Entity Construction and Entity-based Overlay Construction in Gaia.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#574]
This is the new overlay generation workflow Nu will offer as well -

- [x] Allow user to create a new entity that approximates the overlay the user wishes to use in the project.
- [x] Allow user to add whatever facets are needed to refine that entity further toward the idea.
- [ ] Allow user to create a new overlay from the selected entity's configuration.
- [ ] Allow user to create a new entity from this or another overlay.
- [x] Allow user to run game to check behavior.
- [ ] Track changes to overlays, synchronizing the unchanged portion of existing entities to them from the changed overlays.

BONUS:

- [ ] Experiment with seeing if overlays can be applied not just to individual entities, but to entities with children as well, constructing children if they are missing. This could afford more Prefab-style of overlays without having to create an entirely new first-class engine feature.
- [ ] See if there's a way to instantiate certain types of prefabs as temporary entities so they can be viewed and edited in the viewport.

**Comment by bryanedds** [comment]
This is the more ambitious entity templating feature that we've decided to archive -

```
This is the new template generation workflow Nu will offer as well -

- [x] Allow user to create a new entity that approximates the template the user wishes to stamp into the project.
- [x] Allow user to add whatever facets and child entities needed to refine that entity further toward the idea.
- [ ] Allow user to create a new template from the selected entity's configuration and children (similar to prefabs).
- [ ] Allow user to create a new entity from this or another template.
- [x] Allow user to run game to check behavior.
- [ ] Track changes to templates, synchronizing the unchanged portion of existing entities to them from the changed templates.
```

**Comment by bryanedds** [comment]
This is archived as well -

```
This is the new dispatcher generation workflow Nu will offer users -

- [x] Allow user to have an idea for a new simulation phenomenon in editor.
- [ ] Allow user to generate a new EntityDispatcher with a given name, facets, and dispatcher super-type, inserting file into fsproj and opening the file (hopefully landing it in Visual Studio).
- [x] Allow user to reload game code with the new dispatcher available for creation in Gaia.
```

**Comment by AERCR3** [comment]
Hello, I've been following Nu engine for a long time, can I integrate a skeletal animation environment for 2D game development? Using the spine runtime or [SpriteStudio6-SDK](https://github.com/SpriteStudio/SpriteStudio6-SDK)

**Comment by bryanedds** [comment]
> Hello, I've been following Nu engine for a long time, can I integrate a skeletal animation environment for 2D game development? Using the spine runtime or [SpriteStudio6-SDK](https://github.com/SpriteStudio/SpriteStudio6-SDK)

Very likely this will work out fine. Pop into our discord so we can talk over the details - https://discord.gg/xd6RqAnqDD

**Comment by bryanedds** [comment]
> Hello, I've been following Nu engine for a long time, can I integrate a skeletal animation environment for 2D game development? Using the spine runtime or [SpriteStudio6-SDK](https://github.com/SpriteStudio/SpriteStudio6-SDK)

Sorry, our new discord invite link is here - https://discord.gg/hfPAjtHpb

Also, we are investigating SpriteStudio integration as well - https://github.com/bryanedds/Nu/issues/616

**Comment by bryanedds** [comment]
We're taking a different approach than the one outlined here.
