### ISSUE TITLE
Strangely 'skewed' text if user uses SDL2 TTF > 2.0.15.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#587]
This text rendering bug was reported by Corin on nixos -

![image](https://github.com/bryanedds/Nu/assets/1625560/072c6a26-fe84-490b-930b-be8890d3b32c)

However, I couldn't reproduce it either on Win or Ubuntu, so I couldn't proceed.

But today, I happened upon a similar looking bug here -

![image](https://github.com/bryanedds/Nu/assets/1625560/4c0816ef-366a-4af9-9892-bc0c16b9154d)

Since this affects ImGui rendering, I'm now guessing it has something to do with an uninitialized uniform for the sprite batch shader, or perhaps a packing issue for sprite batch vertices.

**Comment by bryanedds** [comment]
Actually, this is very strange because as it turns out, imgui uses a totally different shader for rendering than sprites...

**Comment by bryanedds** [comment]
It's possible these issues the two images aren't related.

**Comment by bryanedds** [comment]
It appears to me that the issue is to do with imgui indices overflowing their 16-bit boundaries, like what is reported here - https://github.com/ocornut/imgui/issues/2504

**Comment by bryanedds** [comment]
I think the underlying issue is that I'm not accounting for index offsets properly as perhaps I've done something different than this code - https://github.com/veldrid/veldrid/blob/20821757d1e88e72219958c9e4e79edfb955f893/src/Veldrid.ImGui/ImGuiRenderer.cs

**Comment by bryanedds** [comment]
The ImGui portion of this bug is fixed - 
![image](https://github.com/bryanedds/Nu/assets/1625560/1d798942-cab8-4504-95a9-409dc2ee722e)
But I doubt this addresses the issue in the first screen shot since they are likely two different bugs.

**Comment by bryanedds** [comment]
This bug was marked as linux as it's only happening on linux as of now.

**Comment by reinux** [comment]
[This link](https://hg.hedgewars.org/hedgewars/rev/c4561095666a) from the second one you posted might be what we're looking for:

```pas
--- a/hedgewars/uRenderUtils.pas	Fri May 20 17:24:14 2022 -0400
+++ b/hedgewars/uRenderUtils.pas	Tue Jul 26 12:37:17 2022 +0200
@@ -188,9 +188,9 @@
     for iY:= srcY to lY do
         begin
         // src pixel index
-        spi:= iY * src^.w  + iX;
+        spi:= iY * src^.pitch div 4  + iX;
         // dest pixel index
-        dpi:= (iY + dY) * dest^.w + (iX + dX);
+        dpi:= (iY + dY) * dest^.pitch div 4 + (iX + dX);
 
         // get src alpha (and set it as target alpha for now)
         aT:= (srcPixels^[spi] and AMask) shr AShift;
```

Specifically, the `src^.pitch div 4` expressions in the changed lines. I'm assuming the `div 4` is to account for RGBA?

My gut tells me this might have something to do with differences in the way `malloc` works on Linux: it doesn't zero out the memory like it does on Windows. So some values might be receiving the "correct" zero value on Windows, whereas on Linux, it's being assigned whatever bits happen to be in that address at the time. Not sure how exactly that would affect it here, but I've seen this be the source of porting issues in the past.

**Comment by bryanedds** [comment]
I don't actually see where we would utilize a pitch in the existing code now that I drill into it. Can you highlight a specific line of interest in our code to detail what you mean by something not being zero'd?

**Comment by bryanedds** [comment]
A couple of nixos users downgraded their SDL2_TTF install to 2.0.15 and this resolved the issue for them. To me, this indicates a regression in SDL2 TTF rather than an issue in Nu. Should we just explicitly specify the version number in the install scripts until either we figure out a workaround in Nu or a version of SDL2 TTF with the regression fixed appears?

**Comment by bryanedds** [comment]
Doing a hex compare of the text surface pixels produced by SDL2 TTF 2.0.15 and 2.0.20.2 shows that each one is producing different data. However, the SDL_PixelFormat for each is the same -

2.0.15:
![image](https://github.com/bryanedds/Nu/assets/1625560/b030d635-7c95-483a-ab6e-e036b7fa28b0)

2.0.20.2:
![image](https://github.com/bryanedds/Nu/assets/1625560/aee9d807-bb0b-4329-b832-40ab377a9561)
