### ISSUE TITLE
Start-up exception on end-user's NVidia linux system.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#810]
![image](https://github.com/bryanedds/Nu/assets/1625560/a3630d6d-ccae-4723-9719-7fa3fb88e8e5)

**Comment by reinux** [comment]
Apparently I lied, because it seems to work just fine on my AMD Linux machine now. In fact, unless I'm mistaken, startup is much faster than on Windows.

**Comment by bryanedds** [comment]
Closed as likely environment issue. Reopen if demonstrably otherwise.

**Comment by bryanedds** [comment]
Reopening since we've not yet found the environmental issue.

**Comment by bryanedds** [comment]
On my local NV linux, I am getting a crash when the following is invoked -

`Gl.TexParameter (TextureTarget.Texture2d, TextureParameterName.TextureMaxAnisotropy, Constants.Render.TextureAnisotropyMax)`

So I added a line of code to check for the GL_ARB_texture_filter_anisotropic extension and sure enough, it wasn't there.

This is an ubuquitous extension (https://www.khronos.org/opengl/wiki/Ubiquitous_Extension), so any environment that doesn't support it is considered inadequately implemented.

**Comment by reinux** [comment]
It seems to need `libX11` for whatever reason on my nvidia machine running Wayland. My laptop running AMD but virtually the same environment otherwise doesn't seem to have that issue. Not sure why.

I think we can close for now; this is one of those things that should need to go on our list of dependencies.

**Comment by bryanedds** [comment]
Reopening because this needs a solution that we can provide to others in terms of an update install script or something.

**Comment by bryanedds** [comment]
So I managed to get Nu running on NVidia Linux. If we come up with an install script alteration that will keep others from encountering it, we should consider modifying the script to utilize it.

**Comment by bryanedds** [comment]
> On my local NV linux, I am getting a crash when the following is invoked -
> 
> `Gl.TexParameter (TextureTarget.Texture2d, TextureParameterName.TextureMaxAnisotropy, Constants.Render.TextureAnisotropyMax)`
> 
> So I added a line of code to check for the GL_ARB_texture_filter_anisotropic extension and sure enough, it wasn't there.
> 
> This is an ubuquitous extension (https://www.khronos.org/opengl/wiki/Ubiquitous_Extension), so any environment that doesn't support it is considered inadequately implemented or configured.

Update to latest Ubuntu and this seems to have gone away.

**Comment by bryanedds** [comment]
Updated script to attempt to fix this for exclusive Wayland users.
