### ISSUE TITLE
Potential inset orientation issue.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#865]
Currently, it appears that 2D inset values reference texels with top-left as origin whereas it would make more sense in many cases (and be more consistent with other systems) with bottom-left as origin. Let's consider modifying the sprite rendering pipeline to change this.

**Comment by bryanedds** [comment]
The only nice thing I can say about how it currently works is that it matches how nearly all paint / image editing programs work.

**Comment by bryanedds** [comment]
CC'ing https://github.com/mapeditor/tiled/issues/249#issuecomment-2334921306 since this is the issue that once again brought the subject to the forefront of my mind.

**Comment by bryanedds** [comment]
Maybe we just accept that this will be a problem until the end of time? 2D authoring programs will always have their Y's inverted compared to engine representations. This is inconsistent frame representation is pretty much accepted as-is in the 3D authoring vs. engine space. However, it's a real problems because even to this day, there is a minor enhancement I'd like to add to Omni Blade's map generation code that I just can't wrap my head around due to this aspect causing a little too much cognitive load for me to carry comfortably and thus remains unimplemented.

**Comment by bryanedds** [comment]
The best way I can describe this phenomenon is that inset is in 'authoring space' or 'paint program space'.  In terms of the engine itself, it seems weird and inconsistent. But in terms of using it in tandem with image authoring, it can be a lot more intuitive.

**Comment by bryanedds** [comment]
Inset values are also in pixel coordinates rather than unit coordinates. so maybe the current representation makes a little more sense than the alternative.

**Comment by bryanedds** [comment]
Let's close this as not improvable.

**Comment by divSelector** [comment]
rip
